# model_list:
#   - model_name: gpt-4
#     litellm_params:
#       model: openai/gpt-4
#       api_key: os.environ/OPENAI_API_KEY

#   - model_name: gpt-3.5-turbo
#     litellm_params:
#       model: openai/gpt-3.5-turbo
#       api_key: os.environ/OPENAI_API_KEY

#   - model_name: claude-3-opus
#     litellm_params:
#       model: anthropic/claude-3-opus-20240229
#       api_key: os.environ/ANTHROPIC_API_KEY

#   - model_name: claude-3-sonnet
#     litellm_params:
#       model: anthropic/claude-3-sonnet-20240229
#       api_key: os.environ/ANTHROPIC_API_KEY

  # Add more models as needed (Ollama, Azure, etc.)
  # - model_name: ollama-llama2
  #   litellm_params:
  #     model: ollama/llama2
  #     api_base: http://host.docker.internal:11434

litellm_settings:
  drop_params: true
  set_verbose: false

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
